-- ============================================================
--  우리 둘만의 공간 — Supabase 스키마
--  Supabase 대시보드 > SQL Editor 에 통째로 붙여넣고 RUN
-- ============================================================

-- 1) 기념일 (D-day / 캘린더에 표시)
create table if not exists anniversaries (
  id          bigint generated by default as identity primary key,
  title       text not null,
  date        date not null,
  emoji       text default '💗',
  yearly      boolean default false,            -- 매년 반복(생일 등)
  created_at  timestamptz default now()
);

-- 2) 버킷리스트 (카테고리: travel/buy/eat/do)
create table if not exists bucket_items (
  id          bigint generated by default as identity primary key,
  category    text not null default 'do',       -- travel | buy | eat | do
  title       text not null,
  done        boolean default false,
  done_at     timestamptz,
  created_by  text,
  created_at  timestamptz default now()
);

-- 3) 한줄일기 / 편지
create table if not exists diary_entries (
  id          bigint generated by default as identity primary key,
  author      text,                             -- 작성자 이메일
  mood        text default '🙂',
  content     text not null,
  entry_date  date default current_date,
  created_at  timestamptz default now()
);

-- 4) 오늘의 기분 (사람당 한 줄, upsert)
create table if not exists statuses (
  user_email  text primary key,
  mood        text default '😊',
  message     text default '',
  updated_at  timestamptz default now()
);

-- 5) 콕 찌르기 (보고싶어! 알림)
create table if not exists pokes (
  id          bigint generated by default as identity primary key,
  from_email  text,
  message     text default '보고싶어! 💗',
  created_at  timestamptz default now()
);

-- 6) 추억 사진첩
create table if not exists photos (
  id          bigint generated by default as identity primary key,
  url         text not null,                    -- Storage public URL
  caption     text default '',
  taken_date  date,
  created_by  text,
  created_at  timestamptz default now()
);

-- 7) 우리 발자취 타임라인
create table if not exists footprints (
  id          bigint generated by default as identity primary key,
  title       text not null,
  place       text default '',
  note        text default '',
  emoji       text default '📍',
  date        date,
  created_at  timestamptz default now()
);

-- 8) 데이트 룰렛 항목 (food / activity)
create table if not exists roulette_options (
  id          bigint generated by default as identity primary key,
  category    text not null default 'activity', -- food | activity
  text        text not null,
  created_at  timestamptz default now()
);

-- ============================================================
--  v2 추가 컬럼 (재실행 안전 — 이미 있으면 무시)
-- ============================================================
alter table anniversaries add column if not exists repeat text default 'none'; -- none|weekly|monthly|yearly
alter table bucket_items  add column if not exists subcat   text;
alter table bucket_items  add column if not exists country  text;   -- 국내|국외
alter table bucket_items  add column if not exists region   text;
alter table bucket_items  add column if not exists want_date date;
alter table bucket_items  add column if not exists url      text;
alter table photos        add column if not exists title    text;
alter table footprints    add column if not exists photo_url text;

-- 기존 yearly=true 데이터를 repeat='yearly' 로 한 번 정리
update anniversaries set repeat = 'yearly' where yearly = true and (repeat is null or repeat = 'none');

-- ============================================================
--  RLS (Row Level Security)
--  로그인한 사용자(우리 둘)만 모든 작업 허용
-- ============================================================
do $$
declare t text;
begin
  foreach t in array array[
    'anniversaries','bucket_items','diary_entries','statuses',
    'pokes','photos','footprints','roulette_options'
  ]
  loop
    execute format('alter table %I enable row level security;', t);
    execute format('drop policy if exists "couple_all" on %I;', t);
    execute format(
      'create policy "couple_all" on %I for all to authenticated using (true) with check (true);', t
    );
  end loop;
end $$;

-- ============================================================
--  실시간(Realtime) 켜기 — 상대가 수정하면 바로 반영/알림
-- ============================================================
do $$
declare t text;
begin
  foreach t in array array[
    'anniversaries','bucket_items','diary_entries','statuses',
    'pokes','photos','footprints','roulette_options'
  ]
  loop
    begin
      execute format('alter publication supabase_realtime add table %I;', t);
    exception when duplicate_object then null;
    end;
  end loop;
end $$;

-- ============================================================
--  기본 룰렛 항목 살짝 넣어두기 (원하면 앱에서 추가/삭제)
-- ============================================================
-- 테이블이 비어있을 때만 기본 항목 추가 (재실행 시 중복 방지)
insert into roulette_options (category, text)
select v.category, v.text from (values
  ('food','떡볶이'),('food','초밥'),('food','파스타'),('food','마라탕'),
  ('food','삼겹살'),('food','치킨'),('food','국밥'),('food','햄버거'),
  ('activity','영화보기'),('activity','카페 가기'),('activity','드라이브'),
  ('activity','집에서 뒹굴기'),('activity','산책'),('activity','보드게임'),
  ('activity','전시회'),('activity','노래방')
) as v(category, text)
where not exists (select 1 from roulette_options);

-- ============================================================
--  사진 저장용 Storage 버킷
--  (대시보드 Storage 에서 'photos' 버킷을 Public 으로 만들어도 됩니다)
-- ============================================================
-- 권한 문제로 실패해도 전체가 롤백되지 않도록 감쌈
do $$
begin
  insert into storage.buckets (id, name, public) values ('photos','photos', true) on conflict (id) do nothing;
exception when others then null;
end $$;

do $$
begin
  drop policy if exists "photos_read" on storage.objects;
  create policy "photos_read"   on storage.objects for select using (bucket_id = 'photos');
  drop policy if exists "photos_write" on storage.objects;
  create policy "photos_write"  on storage.objects for insert to authenticated with check (bucket_id = 'photos');
  drop policy if exists "photos_delete" on storage.objects;
  create policy "photos_delete" on storage.objects for delete to authenticated using (bucket_id = 'photos');
exception when others then null;
end $$;
